# Generated by Django 5.1.7 on 2025-04-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0003_equipamento_tombamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('disponível', 'Disponível'), ('emprestado', 'Emprestado'), ('desligado', 'Desligado')], max_length=20),
        ),
    ]
